name: Publish DBT docs

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  id-token: write

jobs:
  publish_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "key.json"
          json: '{"name":"Igor", "password":"Testsss"}'
          dir: 'keys/'

      - name: Prepare Path
        run: |
          ls keys
          cat ./keys/key.json

